import Head from "next/head";
import TimeSlotMain from "../components/timeSlotMain";
export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Basil - Javascript Practical Test</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <section className="h-screen bg-gradient-to-r from-green-400 to-blue-500">
        <div className="container mx-auto px-4 h-full flex justify-center content-center items-center">
          <TimeSlotMain />
        </div>
      </section>
    </>
  );
}
